install.packages('foreach')
install.packages('doSNOW')
install.packages('FNN')
install.packages('HHG')
install.packages('minerva')
install.packages('energy')
install.packages('copula')
install.packages('ks')
install.packages("C:/Users/a0123862/Desktop/simulation codes/mJMI_0.1.0.zip", repos = NULL, type = "win.binary")
